krest1k
beluga161215q
•
:thumbsup: дилдо в жопе

скит юид 11 [NL],  — 0:22

krest1k [FMBS],  — 9:38

скит юид 11 [NL],  — 13:25
привет
скит юид 11
 начал звонок, который продлился 18 минут. — 13:25
скит юид 11 [NL],  — 13:30
Тип вложенного файла: archive
gamesense-menu-remake-csgo-master.zip
390.02 KB
скит юид 11 [NL],  — 13:38
name: Build DLL

on:
  push:
    branches:
      
main
master
pull_request:
workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      
name: Checkout
      uses: actions/checkout@v4

      
name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

      
name: Build Release x64
      run: |
        msbuild IdaLovesMe.sln ^/p:Configuration=Release ^/p:Platform=x64 ^/m

      
name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: IdaLovesMe-DLL
        path: |/Release//.dll
          /x64/Release//.dll
krest1k [FMBS],  — 13:38
Версия Minecraft - 1.21.1
Mod Loader - NeoForge 21.1.186
скит юид 11 [NL],  — 13:38
name: Build DLL

on:
  push:
    branches:
      - main

Новый текстовый документ (2).txt
1 кб
скит юид 11
 начал звонок, который продлился 9 минут. — 14:21
скит юид 11 [NL],  — 14:23
github.com/luadef-dev
ты че
krest1k [FMBS],  — 15:39
всё
я тут
скит юид 11 [NL],  — 15:43
о
ок
ща
пара минут
krest1k [FMBS],  — 15:43
jr
скит юид 11
 начал звонок, который продлился 43 минуты. — 15:47
скит юид 11 [NL],  — 15:53
Тип вложенного файла: unknown
BrutalityInjector.exe
1.02 MB
-allow_third_party_software
krest1k [FMBS],  — 16:15
Run msbuild IdaLovesMe.sln ^
MSBuild version 18.6.3+84d3e95b4 for .NET Framework
MSBUILD : error MSB1008: Only one project can be specified.
    Full command line: '"C:\Program Files\Microsoft Visual Studio\18\Enterprise\MSBuild\Current\Bin\MSBuild.exe" IdaLovesMe.sln ^'
  Switches appended by response files:
'' came from 'C:\Program Files\Microsoft Visual Studio\18\Enterprise\MSBuild\Current\Bin\MSBuild.rsp'
Switch: ^

For switch syntax, type "MSBuild -help"
/p:Configuration=Release: D:\a_temp\dbd69249-725c-4823-b5cb-6e99246950d5.ps1:3
Line |
   3 |    /p:Configuration=Release ^
     |    ~~~~~~~~
     | The term '/p:Configuration=Release' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.
Error: Process completed with exit code 1.
https://github.com/krest1k123/6767/
GitHub
GitHub - krest1k123/6767
Contribute to krest1k123/6767 development by creating an account on GitHub.
GitHub - krest1k123/6767
https://github.com/krest1k123/6767
GitHub
GitHub - krest1k123/6767
Contribute to krest1k123/6767 development by creating an account on GitHub.
Contribute to krest1k123/6767 development by creating an account on GitHub.
https://github.com/krest1k123/6767
https://github.com/krest1k123/6767
GitHub
GitHub - krest1k123/6767
Contribute to krest1k123/6767 development by creating an account on GitHub.
Contribute to krest1k123/6767 development by creating an account on GitHub.
https://github.com/krest1k123/6767
GitHub
GitHub - krest1k123/6767
Contribute to krest1k123/6767 development by creating an account on GitHub.
Contribute to krest1k123/6767 development by creating an account on GitHub.
https://github.com/krest1k123/6767
GitHub
GitHub - krest1k123/6767
Contribute to krest1k123/6767 development by creating an account on GitHub.
Contribute to krest1k123/6767 development by creating an account on GitHub.
https://github.com/krest1k123/6767
GitHub
GitHub - krest1k123/6767
Contribute to krest1k123/6767 development by creating an account on GitHub.
Contribute to krest1k123/6767 development by creating an account on GitHub.
https://github.com/krest1k123/6767
GitHub
GitHub - krest1k123/6767
Contribute to krest1k123/6767 development by creating an account on GitHub.
Contribute to krest1k123/6767 development by creating an account on GitHub.
https://github.com/krest1k123/6767
GitHub
GitHub - krest1k123/6767
Contribute to krest1k123/6767 development by creating an account on GitHub.
Contribute to krest1k123/6767 development by creating an account on GitHub.
https://github.com/krest1k123/6767
GitHub
GitHub - krest1k123/6767
Contribute to krest1k123/6767 development by creating an account on GitHub.
Contribute to krest1k123/6767 development by creating an account on GitHub.
https://github.com/krest1k123/6767
GitHub
GitHub - krest1k123/6767
Contribute to krest1k123/6767 development by creating an account on GitHub.
Contribute to krest1k123/6767 development by creating an account on GitHub.
скит юид 11 [NL],  — 16:20
name: Build DLL

on:
  push:
    branches:
      - main

Новый текстовый документ (2).txt
1 кб
krest1k [FMBS],  — 16:23
Run msbuild IdaLovesMe.sln ^
  
MSBuild version 18.6.3+84d3e95b4 for .NET Framework
Build started 6/13/2026 9:21:56 AM.
     1>Project "D:\a\6767\6767\IdaLovesMe.sln" on node 1 (default targets).
     1>ValidateSolutionConfiguration:

message.txt
12 кб
скит юид 11 [NL],  — 16:23
name: Build DLL

on:
  push:
    branches:
      - main

Новый текстовый документ (2).txt
1 кб
krest1k [FMBS],  — 16:24
Run msbuild IdaLovesMe.sln ^
MSBuild version 18.6.3+84d3e95b4 for .NET Framework
Build started 6/13/2026 9:24:16 AM.

     1>Project "D:\a\6767\6767\IdaLovesMe.sln" on node 1 (default targets).
     1>ValidateSolutionConfiguration:

message.txt
12 кб
скит юид 11 [NL],  — 16:25
name: Build DLL

on:
  push:
    branches:
      - main

Новый текстовый документ (2).txt
1 кб
krest1k [FMBS],  — 16:27
Run msbuild IdaLovesMe.sln ^
  
MSBuild version 18.6.3+84d3e95b4 for .NET Framework
Build started 6/13/2026 9:26:02 AM.
     1>Project "D:\a\6767\6767\IdaLovesMe.sln" on node 1 (default targets).
     1>ValidateSolutionConfiguration:

message.txt
12 кб
скит юид 11 [NL],  — 16:27
name: Build DLL

on:
  push:
    branches:
      - main

Новый текстовый документ (2).txt
2 кб
krest1k [FMBS],  — 16:28
Run msbuild IdaLovesMe.sln ^
  
MSBuild version 18.6.3+84d3e95b4 for .NET Framework
Build started 6/13/2026 9:27:47 AM.
     1>Project "D:\a\6767\6767\IdaLovesMe.sln" on node 1 (default targets).
     1>ValidateSolutionConfiguration:

message.txt
10 кб
Clyde
БОТ
 — 16:30
Похоже, что вы более 3 минут единолично занимали линию. Служба контроля трафика попросила отключить вас для экономии. Трафик счёт любит!
Только вы видите это сообщение • Нажмите здесь, чтобы убрать его
Вы пропустили звонок от 
скит юид 11
, который длился несколько секунд. — 18:16
скит юид 11
 начинает звонок. — 18:16
скит юид 11 [NL],  — 18:19
name: Build DLL

on:
  push:
    branches:
      - main

Новый текстовый документ (2).txt
3 кб
скит юид 11 [NL],  — 18:29
Тип вложенного файла: archive
dkjfhdgvsuekjrhgvhvrhrjhfjhwvriksgjmwkrsjvrjhgsrjfsrf-main (1).zip
3.45 MB
скит юид 11 [NL],  — 18:39
Изображение
krest1k [FMBS],  — 18:40
Изображение
krest1k [FMBS],  — 18:56
1518285000
krest1k [FMBS],  — 19:08
Run nuget restore YourProjectName.sln

Input file does not exist: YourProjectName.sln.
Error: Process completed with exit code 1.
скит юид 11 [NL],  — 19:15
Run nuget restore YourProjectName.sln

Input file does not exist: YourProjectName.sln.
Error: Process completed with exit code 1.
name: Build C++ DLL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      
name: Checkout repository
      uses: actions/checkout@v4

      
name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

      
name: Show solution files
      shell: pwsh
      run: |
        Get-ChildItem -Path . -Filter *.sln -Recurse | Select-Object FullName

      
name: Build solution
      shell: cmd
      run: msbuild darkside_sdk.sln /m /p:Configuration=Release /p:Platform=x64

      
name: Upload DLL artifacts
      uses: actions/upload-artifact@v4
      with:
        name: darkside_sdk-release
        path: output\Release*.dll
        if-no-files-found: error
name: Build C++ DLL

on:
  push:
    branches: [ "main" ]
  pull_request:

Новый текстовый документ (2).txt
1 кб
krest1k [FMBS],  — 19:17
Run msbuild darkside_sdk.sln /m /p:Configuration=Release /p:Platform=x64
  
MSBuild version 17.14.40+3e7442088 for .NET Framework
Build started 6/13/2026 12:16:10 PM.
     1>Project "D:\a\sdgsdfgdfg\sdgsdfgdfg\darkside_sdk.sln" on node 1 (default targets).
     1>ValidateSolutionConfiguration:

message.txt
22 кб
скит юид 11 [NL],  — 19:18
name: Build C++ DLL

on:
  push:
    branches:
      - main

Новый текстовый документ (2).txt
1 кб
﻿
name: Build C++ DLL

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Install libraries
      shell: cmd
      run: |
        vcpkg install protobuf:x64-windows
        vcpkg install freetype:x64-windows

    - name: Build
      shell: cmd
      run: |
        msbuild darkside_sdk.sln ^
        /m ^
        /p:Configuration=Release ^
        /p:Platform=x64 ^
        /p:VcpkgEnabled=true

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: darkside_sdk
        path: |
          **/*.dll
